services:
  api:
    build: .
    container_name: ai_chat_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis
    volumes:
      - ".:/app:rw"

  redis:
    image: redis:7
    container_name: ai_chat_redis
    ports:
      - "6379:6379"

  db:
    image: pgvector/pgvector:pg16
    container_name: ai_chat_db
    environment:
      POSTGRES_DB: ai_chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: