"""fk stuff

Revision ID: 121539519010
Revises: 043ee97e4d77
Create Date: 2026-08-04 16:03:42.743561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '121539519010'
down_revision: Union[str, Sequence[str], None] = '043ee97e4d77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('documents_user_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('webhooks_user_id_fkey'), 'webhooks', type_='foreignkey')
    op.create_foreign_key(None, 'webhooks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webhooks', type_='foreignkey')
    op.create_foreign_key(op.f('webhooks_user_id_fkey'), 'webhooks', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_user_id_fkey'), 'documents', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
